### Login for bimuser01
POST http://localhost:8080/realms/bimevents/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=bimuser01&password=bimuser01!&client_id=example-client&scope=openid profile email 

> {%
    client.global.set("access_token", response.body.access_token);
%}

### Login for bimuser02
POST http://localhost:8080/realms/bimevents/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=bimuser02&password=bimuser02!&client_id=example-client&scope=openid profile email

> {%
    client.global.set("access_token", response.body.access_token);
%}

### Create plan
POST http://localhost:5111/plan/create
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "planName": "My New Building Plan"
}

> {%
    client.global.set("planId", response.body.planId);
%}

### Update Roof Specification
POST http://localhost:5111/plan/updateroofspecification
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "planId": "{{planId}}",
  "roofSpecification": {
    "snowLoadKiloNewtonPerM2": 1,
    "windUpliftKiloNewtonPerM2": 1
  }
}

### Update Roof Specification
POST http://localhost:5111/plan/updateroofspecification
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "planId": "{{planId}}",
  "roofSpecification": {
    "snowLoadKiloNewtonPerM2": 1.8,
    "windUpliftKiloNewtonPerM2": 1.5
  }
}

### Get Plan
GET http://localhost:5111/plan/{{planId}}

### Get Plan Activity
GET http://localhost:5111/plan/activity/{{planId}}

### Get All Plans
GET http://localhost:5111/plan/all

### Get Plan Activity for specific plan
GET http://localhost:5111/plan/activity/{{planId}}

### Get All User Activities
GET http://localhost:5111/useractivity

### Get Specific User Activity
GET http://localhost:5111/useractivity/{{planId}}
